# .github/workflows/build.yml
name: Deploy

on: push

jobs:
  deploy-ssh:
    name: Deploy Via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Creating Key Files
        run: |
          echo "${{ secrets.SSH_TARGET_KEY }}" > /tmp/Target.pem
          echo "${{ secrets.SSH_BASTION_KEY }}" > /tmp/Bastion.pem

      - name: Adding to Known Hosts
        run: |
          mkdir ~/.ssh
          echo "${{SSH_KNOWN_HOSTS}}" > ~/.ssh/known_hosts

      - name: Deploying with scp
        run: scp -o "proxycommand ssh -W %h:%p -i /tmp/Bastion.pem ${{ secrets.SSH_BASTION_USER }}@${{ secrets.SSH_BASTION_HOST }}" -i /tmp/Target.pem index ${{ secrets.SSH_TARGET_USER }}@${{ secrets.SSH_TARGET_HOST }}:${{ secrets.DEST_TARGET_PATH }}
