# .github/workflows/build.yml
name: Deploy

on: push

jobs:
  deploy-ssh:
    name: Deploy Via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Creating Key Files
        run: |
          echo "${{ secrets.SSH_TARGET_KEY }}" > /tmp/Target.pem
          echo "${{ secrets.SSH_BASTION_KEY }}" > /tmp/Bastion.pem
          chmod 400 /tmp/*.pem

      - name: Adding to Known Hosts
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deleting previous stuff from Target
        run: ssh -i /tmp/Target.pem ${{ secrets.SSH_TARGET_USER }}@${{ secrets.SSH_TARGET_HOST }} -o "proxycommand ssh -W %h:%p -i /tmp/Bastion.pem ${{ secrets.SSH_BASTION_USER }}@${{ secrets.SSH_BASTION_HOST }}" "rm -rf ${{ secrets.DEST_TARGET_PATH }}*"      

      - name: Deploying with scp
        run: scp -o "proxycommand ssh -W %h:%p -i /tmp/Bastion.pem ${{ secrets.SSH_BASTION_USER }}@${{ secrets.SSH_BASTION_HOST }}" -i /tmp/Target.pem * ${{ secrets.SSH_TARGET_USER }}@${{ secrets.SSH_TARGET_HOST }}:${{ secrets.DEST_TARGET_PATH }}

      - name: Deleting Keys
        run: rm /tmp/*.pem

