# .github/workflows/build.yml
name: Deploy

on: push

jobs:
  deploy-ssh:
    name: Deploy Via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name : Install Bastion SSH Key
        uses : shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_BASTION_KEY }}
          known_hosts: unnecessary

      - name : Install SSH Key
        uses : shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_TARGET_KEY }}
          known_hosts: unnecessary

      - name: Adding Bastion to Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_BASTION_HOST }}  >> ~/.ssh/known_hosts

      - name: Adding Target to Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_TARGET_HOST }}  >> ~/.ssh/known_hosts

      - name: Creating Key Files
        run: |
          echo "${{ secrets.SSH_TARGET_KEY }}" > /tmp/Target.pem
          echo "${{ secrets.SSH_Bastion_KEY }}" > /tmp/Bastion.pem

      - name: Creating .ssh/config
        run: |
          echo "Host Bastion
            Hostname ${{ secrets.SSH_BASTION_HOST }}
            User ${{ secrets.SSH_BASTION_USER }}
            IdentityFile /tmp/Bastion.pem
          Host Target
            Hostname ${{ secrets.SSH_TARGET_HOST }}
            User ${{ secrets.SSH_TARGET_USER }}
            IdentityFile /tmp/Target.pem" >> ~/.ssh/config

      - name: Deploying with scp
        run: scp -J Bastion * Target:${{ secrets.DEST_TARGET_PATH }}
